### ISSUE TITLE
Enable styling without a manifest

### ISSUE THREAD

**Issue by gabdube** [balthild/native-dialog-rs#1]
Here's a hack to enable styling without using a manifest: https://github.com/gabdube/native-windows-gui/blob/1.0-prerelease/native-windows-gui/src/win32/mod.rs#L91 

As far as I know, this never caused any problem and you always make it opt-in using features.

**Comment by balthild** [comment]
OK，I'll take a look.

**Comment by balthild** [comment]
I implemented the feature in 0.2.2 in the way described in [this stackoverflow answer](https://stackoverflow.com/a/25271493). Thanks for your suggestion!
