### ISSUE TITLE
Save dialog support?

### ISSUE THREAD

**Issue by francesco-cattoglio** [balthild/native-dialog-rs#11]
Hello,
I was taking a look at the library and if I understand correctly, there is currently no support for a save file dialog.
Is this correct? Are there any plans to support save file dialogs in the near future?

**Comment by balthild** [comment]
I will start to work it out after the refactor (v0.5) is done. Currently this feature is blocked on macOS because AppleScript does not support file types for save dialog. I'm rewriting the macOS implementation with `objc` now.

**Comment by balthild** [comment]
I have some difficult implementing file saving dialogs for linux and unix. kdialog and zenity don't verify the file extension user have input, nor add extension to the resulting path based on the file type selected by user. They even don't provide a way to let the caller know which file type user have selected. The dropdown menu only affects which files could user see (like open dialog).

Seems like the only way to achieve the functionality is extending `QFileDialog`/`GtkFileChooserDialog` and implementing it myself, with C/C++... should I do it?

**Comment by francesco-cattoglio** [comment]
In my own project I am facing the same issues, and I ended up emulating the proper behavior by:
- creating a file save dialog with zenity
- processing the file chosen by the user, adding the extension if it is not there already
- checking if the file exists, and presenting a second dialog asking for overwrite confirmation

I feel like this is still not optimal, but it is enough for my use case. You might decide to do something similar or implement something using GTK, in the end it is up to you. If you want to implement some functionality in C++ I might be able to help with that. I am not an expert on GTK or QT, but I have successfully mixed Rust and C++ by using the `cxx` crate.

**Comment by balthild** [comment]
I decided to stick with zenity/kdialog because calling QFiledialog/GtkFileChooserDialog requires programs use this crate link against both gtk3 and qt5, which will make this crate too heavy. Showing the warnings dialog of incorrect extension and file exists by myself is a good workaround.

By the way, maybe I could provide a feature gate to switch to QFiledialog/GtkFileChooserDialog implementations for those program didn't aware of "lightweightness".

**Comment by balthild** [comment]
v0.5.0 published
