### ISSUE TITLE
Compilation fails on windows since `wfd` update

### ISSUE THREAD

**Issue by thenlevy** [balthild/native-dialog-rs#14]
The latest `wfd` updates has introduced a new variant for the enum [`wfd::DialogError`](https://docs.rs/wfd/0.1.6/wfd/enum.DialogError.html). This causes compilation to fail on windows due to a [non-exhaustive match in `src/impl/win/file.rs`](https://github.com/balthild/native-dialog-rs/blob/0.4-hotfix/src/impl/win/file.rs#L101)

**Comment by balthild** [comment]
Fixed in v0.4.4
