### ISSUE TITLE
Support modal file dialogs

### ISSUE THREAD

**Issue by maroider** [balthild/native-dialog-rs#16]
Windows dialogs need the handle of the window which the dialog will be modal with. `native-dialog` does not currently support this in any way, which is particularly unfortunate for file dialogs since these are almost always modal.

This will of course require changes to `wfd`.

cc @ben-wallis

**Comment by ben-wallis** [comment]
I'll look into adding this to `wfd`

**Comment by ben-wallis** [comment]
wfd 0.1.7 has been released to add support for providing the owner HWND

https://github.com/ben-wallis/wfd/compare/0.1.6...0.1.7

**Comment by balthild** [comment]
I'm working for the feature, but I'd wonder how to expose appropriate APIs for it.

This feature is platform-specific. Cocoa also have such API to modal the dialog with a window ([runModalForWindow:](https://developer.apple.com/documentation/appkit/nsapplication/1428436-runmodalforwindow?language=objc)), and Zenity/KDialog does not.

Both Win32 API and Cocoa accepts a pointer but their type is different in Rust and belongs to different crates ([HWMD](https://docs.rs/winapi/0.3.9/winapi/shared/windef/type.HWND.html) / [*mut Object](https://docs.rs/objc/0.2.7/objc/runtime/struct.Object.html)). Should I accept a `usize` (seems not safe enough), or should I accept those specific types and make the APIs platform-specific (requires the user to call the APIs with `#[cfg(...)]`)?

**Comment by maroider** [comment]
> Both Win32 API and Cocoa accepts a pointer as parameter for this feature but their type is different in Rust and belongs to different crates ([HWND](https://docs.rs/winapi/0.3.9/winapi/shared/windef/type.HWND.html) / [*mut Object](https://docs.rs/objc/0.2.7/objc/runtime/struct.Object.html)). Should I accept a `usize` (seems not safe enough), or should I accept those specific types and make the APIs platform-specific (requires the user to call the APIs with `#[cfg(...)]`)?

I think there's room for both `#[cfg(...)]`-ed functions and a cross-platform function.

The cross-platform function should take a reference to a type which implements [`HasRawWindowHandle`](https://docs.rs/raw-window-handle/0.3.3/raw_window_handle/trait.HasRawWindowHandle.html). The window types from `winit`, `sdl2`, and `glfw` implement this trait. It should be documented that the function does nothing on Unix-y platforms, if it is impossible to implement.

**Comment by balthild** [comment]
v0.5.3 has been publish. The version supports modal dialogs on Windows.

Modal sheet on macOS will be support later, because I'm spending the New Year in my hometown, and I have no access to my macOS device now...

**Comment by maroider** [comment]
I have a couple of nit-picks:
- I don't think you're supposed to re-export `raw-window-handle`.
- `set_owner` is an unusual name for this, I had expected something along the lines of `set_parent`, as parent-child relationships between windows in Windows are fairly easy to figure out. Window "ownership" in Windows is something I couldn't really find much about when I tried (briefly) looking into it once (some time ago).
- Exposing a _safe_ method which takes a `RawWindowHandle` isn't really a good idea, as it is now up to the caller of the function to ensure that the handle is valid, rather than whomever implements the type which implements `HasRawWindowHandle`.

**Comment by balthild** [comment]
I've made changed according to the suggestions, and published v0.5.4. Thanks!

**Comment by balthild** [comment]
[Modal sheet](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/sheets/) support for macOS is added in v0.6.1
