### ISSUE TITLE
Filter not working with show_open_multiple_file on Mac os

### ISSUE THREAD

**Issue by spineki** [balthild/native-dialog-rs#20]
## Problem:
When using FileDialog with show_open_multiple_file and filters, every document is not clickable, even if it satisfies the filter.

Example:

``` rust
FileDialog::new()
.set_location("~/Desktop")
.add_filter("PDF File", &["pdf"])
.show_open_multiple_file()
```
won't let to select pdf.

## Fix proposition:

I tried to changed in native-dialog-rs/src/dialog_impl/mac/file.rs
in impl DialogImpl for OpenMultipleFile, function `show`:

`panel.set_allowed_file_types(get_file_type_dropdown_items(&self.filters));`

to   `panel.set_allowed_file_types(get_all_allowed_types(&self.filters));`

which mimic the code of OpenSingleFile.

This fixes solves my problem.

**Comment by balthild** [comment]
Looks like it's a typo. Fixed in v0.5.7. Thanks!
