### ISSUE TITLE
Unexpected `file://` prepended to `PathBuf` returned from `show_open_single_dir()`

### ISSUE THREAD

**Issue by theRookieCoder** [balthild/native-dialog-rs#22]
The function `FileDialog.show_open_single_dir()` prepends `"file://"` to the `PathBuf` returned. This doesn't make any sense because a _directory_ should be returned

Platform: macOS

**Comment by balthild** [comment]
I've tested just now, and find that all `show_*` methods on FileDialog return paths starts with `file://`. This behavior does not appear when I wrote this crate. Seems that it's macOS update that causes this issue.

**Comment by balthild** [comment]
Should be fixed in v0.5.8
