### ISSUE TITLE
Refactor the implementation for macOS

### ISSUE THREAD

**Issue by balthild** [balthild/native-dialog-rs#5]
Currently, the macOS impl is built on top of `osascript`, or AppleScript. However, AppleScript have some problems:

- Do not support specifying file types for save dialog ([docs](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW5)).
- Lacks type safe.
- The result must be de/serialized.

A considerable choice is switching to Cocoa APIs. This can be done with the `objc` and `cocoa` crates. For example:

```rust
use cocoa::foundation::NSInteger;
use objc::runtime::Object;

pub(crate) struct NSSavePanel(*mut Object);

impl NSSavePanel {
    pub(crate) fn new() -> Self {
        let cls = class!(NSSavePanel);
        let ptr = unsafe { msg_send![cls, savePanel] };
        Self(ptr)
    }

    pub(crate) fn run_modal(self) -> NSInteger {
        unsafe { msg_send![self.0, runModal] }
    }

    // ...
}
```

However, this way have a critical problem - the Cocoa APIs must be called from main thread, otherwise there will be a panic. <del>In `iced`, we have no control that which thread our code would be called (due to the nature of tokio/async-std multithreading runtime).</del> (Update: This is not true. In iced-winit, `Application::update` will always be called in the event loop.) And it seems impossable to "run a function as a subprocess" in POSIX process model.

A compromise may be providing feature gate with options:

- AppleScript implementation: can be called outside main thread and no save dialog.
- Cocoa implementation: must be called from main thread.

**Comment by balthild** [comment]
I've came up with a hacky way. It may not working, and it's really tricky.

1. Make a bin crate that calls Cocoa APIs.
2. Embed output executables of the bin crate into this lib crate.
3. Extract the executables to system tmp folder at runtime.
4. Run the executable to call Cocoa APIs.

If I do so, it should also be provided with a feature gate.

**Comment by balthild** [comment]
A third way, which is less tricky - run python scripts and call Cocoa APIs with PyObjC.

**Comment by francesco-cattoglio** [comment]
A question regarding file types when saving: I have found that the users of my software very often forget about file extensions. In my C++ code I usually just have to read the filename the user chose, manually add the extension, check if the file already exist and use a second prompt to ask overwrite confirmation. If one uses Cocoa API, will the save file dialog itself force the extension to be the correct one and will it automatically detect possible overwrites?

**Comment by balthild** [comment]
> will the save file dialog itself force the extension to be the correct one

Yes. The `NSSaveDialog` prevents users from specifying incorrect extension. For example, if the program ask to save "A.png", and user changed the filename to "A.[ext]" manually, then

- a small dialog will be shown if [ext] is an extension of file types known by macOS, such as "txt", "jpg" or "pdf". The dialog will ask users to "use png" as extension or "use both". If user selects "use png", the panel will return "A.png", otherwise it will return "A.[ext].png".
- the panel will return "A.[ext].png" directly if macOS doesn't know [ext]

Also, if user changed the filename to some strings without an extension, says "A", the panel will return "A.png" directly.

> will it automatically detect possible overwrites

Yes. If there exists a file at the path that the panel is about to return, another small dialog will shown to ask the user whether override the existing file.
