### ISSUE TITLE
Spinning beachball on macOS.

### ISSUE THREAD

**Issue by casperstorm** [balthild/native-dialog-rs#7]
When running the example project, I get a spinning beachball as soon as the file dialog shows up.
Is there any frameworks dependencies I am missing? I have same behaviour with https://github.com/EmbarkStudios/nfd2 which is a bit strange.

**Comment by casperstorm** [comment]
Seemed to be a Iced issue, I got it to work it seems. Thanks for this crate.

**Comment by BrettMayson** [comment]
Having this issue, any one know how to fix? Using 0.5.5

**Comment by balthild** [comment]
Seems like it's the same issue as #23, which is caused by winit. Upgrading winit to v0.26 and this crate to v0.6 rsolves it.
